In [1]:
from tensorflow import keras
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
iris = load_iris()
df_iris = pd.DataFrame(data = iris.data, columns=iris.feature_names)
df_iris['target'] = iris.target
df_iris.head()
data = df_iris.iloc[:,:-1].to_numpy()
target = df_iris.iloc[:,-1].to_numpy()
print(data[:5],target[:5])
print(data.shape,target.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] [0 0 0 0 0]
(150, 4) (150,)


In [ ]:
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)
print(train_input.shape, test_input.shape)

(120, 4) (30, 4)


In [ ]:
sd = StandardScaler()
sd.fit(train_input)
train_input = sd.transform(train_input)
test_input = sd.transform(test_input)

In [ ]:
#로지스틱회귀
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss='log_loss',max_iter=500,tol=1e-3)
sgd.fit(train_input,train_target)
print(sgd.score(train_input,train_target))
print(sgd.score(test_input,test_target))

0.8583333333333333
0.8666666666666667


In [ ]:
#ANN
dense = keras.layers.Dense(3,activation='softmax',input_shape=(4,))
model = keras.Sequential([dense])
model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(train_input,train_target,epochs=500)

Epoch 1/500


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6958 - loss: 0.6768  
Epoch 2/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6542 - loss: 0.6973 
Epoch 3/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6481 - loss: 0.6901 
Epoch 4/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6806 - loss: 0.6992 
Epoch 5/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6683 - loss: 0.6883 
Epoch 6/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7152 - loss: 0.6500 
Epoch 7/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7173 - loss: 0.6446 
Epoch 8/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6852 - loss: 0.6720 
Epoch 9/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7165 - loss: 0.6344 
Epoch 10/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7104 - loss: 0.6494
Epoch 11/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6875 - loss: 0.6723 
Epoch 12/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6635 - loss: 0.6743 


In [ ]:
print(model.evaluate(train_input,train_target))
print(model.evaluate(test_input,test_target))

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9690 - loss: 0.1857  
[0.18892231583595276, 0.9666666388511658]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9667 - loss: 0.1488
[0.14879682660102844, 0.9666666388511658]


In [ ]:
pred = model.predict(test_input)
print(np.round(pred[:5],decimals=3))
pred_idx = np.argmax(pred,axis=1)
print(pred_idx)
print(test_target)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[0.005 0.765 0.23 ]
 [0.993 0.007 0.   ]
 [0.    0.019 0.981]
 [0.006 0.627 0.367]
 [0.    0.658 0.342]]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
