In [4]:
#1번 문제
import pandas as pd

#생선 데이터를 읽고, fish_data에 저장
fish_data = pd.read_csv('https://bit.ly/fish_csv_data')

#특성 선택(Weight, Length, Height, Width) + 첫 100개 샘플만 사용
features = ['Weight', 'Length', 'Height', 'Width']
fish_input = fish_data[features].iloc[:100].to_numpy()

In [5]:
#2번 문제
#타깃을 fish_target에 저장
fish_target = fish_data['Species'].iloc[:100].to_numpy()

In [8]:
#3번 문제
from sklearn.model_selection import train_test_split

#훈련데이터와 테스트데이터로 나누고 shape을 출력
train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, random_state=42)
print(train_input.shape, test_input.shape)
print(train_target.shape, test_target.shape)

(75, 4) (25, 4)
(75,) (25,)


In [9]:
#4번 문제
#훈련데이터와 테스트데이터를 표준화
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [19]:
#5번 문제
#로지스틱 회귀모델을 생성, 훈련 후 훈련데이터와 테스트데이터의 점수를 출력
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(train_scaled, train_target)
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.8
0.76


In [15]:
#6번 문제
import numpy as np

#테스트데이터의 첫 3개의 샘플에 대해 분류 결과와 각 클래스의 확률 출력
print(lr.predict(test_scaled[:3]))
proba = lr.predict_proba(test_scaled[:3])
print(np.round(proba, decimals=3))

['Perch' 'Roach' 'Bream']
[[0.006 0.1   0.55  0.33  0.014]
 [0.116 0.046 0.258 0.393 0.187]
 [0.379 0.297 0.072 0.198 0.055]]


In [20]:
#7번 문제
from scipy.special import softmax

#테스트데이터의 첫 3개의 샘플에 대해 선형방정식의 결과 z 출력
decision = lr.decision_function(test_scaled[:3])
print('z:\n', np.round(decision, 3))

#소프트맥스 함수 이용 확률 출력
proba = softmax(decision, axis=1)
print(np.round(proba, decimals=3))

z:
 [[-2.374  0.365  2.069  1.56  -1.621]
 [-0.312 -1.241  0.484  0.907  0.163]
 [ 0.898  0.654 -0.768  0.25  -1.034]]
[[0.006 0.1   0.55  0.33  0.014]
 [0.116 0.046 0.258 0.393 0.187]
 [0.379 0.297 0.072 0.198 0.055]]
proba_sum
 [1. 1. 1.]
